name: Pipeline CI/CD - Módulo Tarjetas Regalo Zait

on:
  push:
    branches: [ main ]

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    # AQUÍ AGREGAMOS LA VARIABLE PARA QUITAR LA ADVERTENCIA DE NODE.JS
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: 1. Clonar repositorio
        uses: actions/checkout@v4

      - name: 2. Inicializar entorno PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: 3. Análisis Sintáctico (PHP Linting)
        run: find . -name "*.php" -exec php -l {} \;

  continuous-deployment:
    name: Despliegue seguro en producción
    needs: continuous-integration
    runs-on: ubuntu-latest
    # TAMBIÉN LA COLOCAMOS EN LA ETAPA DE DESPLIEGUE
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: 1. Disparar actualización segura en WordPress
        run: |
          curl -X POST "${{ secrets.WP_PUSHER_WEBHOOK_URL }}"
