name: CI/CD - Módulo Tarjetas Regalo Zait

on:
  push:
    branches: [ main ]

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - run: find . -name "*.php" -exec php -l {} \;

  continuous-deployment:
    needs: continuous-integration
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - run: curl -sS "${{ secrets.WP_PUSHER_WEBHOOK_URL }}"
